hello

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,34 @@
 
+# #!/bin/sh
+# . "$(dirname "$0")/_/husky.sh"
+
+# yarn pre-commit
+
+
+
+
 #!/bin/sh
+
+# Source the husky script
 . "$(dirname "$0")/_/husky.sh"
 
+# Patterns of files/directories to exclude
+exclude_patterns="node_modules|dist|\.husky|package-lock.json|package.json"
+
+# Get the list of files to be committed
+files_to_commit=$(git diff --cached --name-only)
+
+# Check if any of the files to be committed match the exclude patterns
+for file in $files_to_commit; do
+    if echo "$file" | grep -E "$exclude_patterns"; then
+        echo "Error: Attempt to commit excluded file $file"
+        exit 1
+    fi
+done
+
+# Run the pre-commit script using yarn
 yarn pre-commit
+
+# Allow the commit if no excluded files are found and pre-commit script passes
+exit 0
+
